-- PostgreSQL Production Database Schema for PayFlow Dynamics
-- Domain Architecture: FinTech & Automated Credit Underwriting (fintech)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "We are a mid-market financial services firm managing over $15M in monthly vendor disbursements across 450 enterprise suppliers. Currently, vendor onboarding, GST tax invoice validation, two-way purchase order reconciliation, and multi-tier CFO payment approvals are handled manually across fragmented email threads and disconnected Excel spreadsheets.   This causes 8 to 12 days of invoice processing lag, duplicate payout errors, missed vendor early-payment discounts, and compliance stress during quarterly financial audits. We need an automated vendor payment orchestration portal with intelligent invoice data extraction, automated PO matching, multi-tier cryptographic approval workflows, and real-time bank payout tracking with an immutable audit trail."

CREATE TABLE IF NOT EXISTS public.fintech_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Requested Loan Amount
  col2_data TEXT NOT NULL, -- Semantic Mapping: CIBIL Tier & Score
  status TEXT NOT NULL,    -- Semantic Mapping: Underwriting Stage
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Risk Engine / Officer
  metric_value TEXT NOT NULL, -- Semantic Mapping: Disbursal SLA
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.fintech_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.fintech_records
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Team and Role Authentication table
CREATE TABLE IF NOT EXISTS public.fintech_users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  badge TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.fintech_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read-write for authenticated users"
  ON public.fintech_users
  FOR ALL
  USING (true)
  WITH CHECK (true);
